language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
# command to run tests
script:
    - make flake8
    - make test
    - make coveralls
after_success:
    - coveralls --ignore-errors
