language: python
python:
  - "3.4"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
  - "pip install python-coveralls"
services:
  - mongodb
before_script:
  - sleep 5
script:
  - make flake8
  - make test
  - make coveralls
after_success:
  - coveralls --ignore-errors
