sudo: false
language: python
python:
- '3.4'
install:
- pip install .
- pip install -r requirements_test.txt
- pip install python-coveralls
services:
- mongodb
script:
- make all
after_success:
- coveralls --ignore-errors
deploy:
  provider: pypi
  user: jakob.grunig
  password:
    secure: HwJbr1np2I9YAl0JgYvu6JwmFKGy/xhgX7htfqT/ViKntwdh/RwJ0FT+ojvzv80doGstixUHLwBqWmcfvnBmCWCgKlRRHXwzHT7ZvGOEPH+lqqe2Hcm7IcNOUD2zo+2CaI3Rqk3N5fpqDTTGA7veqDcHZCvmPOJhPIv9RR9wFZI=
  on:
    tags: true